# Generated by Django 3.1.5 on 2021-02-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('student_Number', models.CharField(max_length=45)),
                ('user_PW', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('admin', models.IntegerField()),
            ],
        ),
    ]
