# Generated by Django 2.1.7 on 2021-02-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_info_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qna',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
