# Generated by Django 3.1.7 on 2021-02-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210225_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('qna_id', models.ForeignKey(db_column='qna_id', on_delete=django.db.models.deletion.CASCADE, related_name='qna', to='crud.qna')),
            ],
        ),
        migrations.CreateModel(
            name='InfoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('info_id', models.ForeignKey(db_column='info_id', on_delete=django.db.models.deletion.CASCADE, related_name='info', to='crud.info')),
            ],
        ),
        migrations.CreateModel(
            name='CrudComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('crud_id', models.ForeignKey(db_column='crud_id', on_delete=django.db.models.deletion.CASCADE, related_name='crud', to='crud.crud')),
            ],
        ),
    ]
