# Generated by Django 3.1.7 on 2021-03-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('crud', '0005_auto_20210307_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudcomment',
            name='name',
        ),
        migrations.AddField(
            model_name='crudcomment',
            name='profile_id',
            field=models.ForeignKey(db_column='CrudComment_profile_id', default=15, on_delete=django.db.models.deletion.CASCADE, related_name='CrudComment_profile', to='account.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crud',
            name='profile_id',
            field=models.ForeignKey(db_column='Crud_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='Crud_profile', to='account.profile'),
        ),
    ]
