# Generated by Django 3.1.7 on 2021-03-07 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('crud', '0006_auto_20210307_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
        migrations.RemoveField(
            model_name='infocomment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qnacomment',
            name='name',
        ),
        migrations.AddField(
            model_name='info',
            name='profile_id',
            field=models.ForeignKey(db_column='Info_profile_id', default=15, on_delete=django.db.models.deletion.CASCADE, related_name='Info_profile', to='account.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infocomment',
            name='profile_id',
            field=models.ForeignKey(db_column='InfoComment_profile_id', default=15, on_delete=django.db.models.deletion.CASCADE, related_name='InfoComment_profile', to='account.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qna',
            name='profile_id',
            field=models.ForeignKey(db_column='Qna_profile_id', default=15, on_delete=django.db.models.deletion.CASCADE, related_name='Qna_profile', to='account.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qnacomment',
            name='profile_id',
            field=models.ForeignKey(db_column='QnaComment_profile_id', default=15, on_delete=django.db.models.deletion.CASCADE, related_name='QnaComment_profile', to='account.profile'),
            preserve_default=False,
        ),
    ]
